version: '2'

services:
  servidor:
    build: .
    container_name: php7_apache
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www/html
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
